#! /bin/sh
# List of all options
options=('1 Laptop(Primary)' '2 External(Primary)' '3 External(Primary) & Laptop' '4 External & Laptop(Primary)')

# Show dmenu list
selected=$(printf '%s\n' "${options[@]}" | rofi -theme ~/.config/rofi/rainbow.rasi -dmenu -i -p "Select display config")

# Run selection
first=$(echo $selected | awk '{ print $1 }')

if [ $first -eq 1 ]; then
	xrandr --output eDP1 --primary --auto
	xrandr --output DP1 --off
	xinput --set-prop 15 "libinput Natural Scrolling Enabled" 1
        $HOME/.config/polybar/launch.sh
	nitrogen --restore
	killall dunst; exec notify-send 'Dunst Restarted!'
elif [ $first -eq 2 ]; then
	xrandr --output DP1 --primary --auto
	xrandr --output eDP1 --off
	nitrogen --restore
        $HOME/.config/polybar/launch.sh
	killall dunst; exec notify-send 'Dunst Restarted!'
elif [ $first -eq 3 ]; then
	xrandr --output DP1 --primary --auto --left-of eDP1
        polybar -c ~/.config/polybar/config.ini eDP1
        $HOME/.config/polybar/launch.sh
	nitrogen --restore
elif [ $first -eq 4 ]; then
	xrandr --output eDP1 --primary --auto --right-of DP1
        $HOME/.config/polybar/launch.sh
	nitrogen --restore
fi
