#! /bin/sh

dotfilesFolder=~/.dotfiles

if [ ! -d $dotfilesFolder ]; then
	# If dotfiles does not exist create it first
	mkdir $dotfilesFolder 
fi

# Copy all scripts to the dotfiles
# But first create a Scripts folder if it does not exist
if [ ! -d $dotfilesFolder/Scripts ]; then
	mkdir $dotfilesFolder/Scripts
fi

# Copy all scripts
cp -r ~/Documents/Scripts/* $dotfilesFolder/Scripts

# Alacritty
# Copy the file
cp ~/.config/alacritty/alacritty.yml $dotfilesFolder/alacritty.yml

# NeoVim
if [ ! -d $dotfilesFolder/nvim ]; then
    mkdir $dotfilesFolder/nvim
fi
# Copy the file
cp ~/.config/nvim/init.vim $dotfilesFolder/nvim/init.vim

# Dunstrc
# Copy the file
cp ~/.config/dunst/dunstrc $dotfilesFolder/dunstrc

# i3config
# Create i3 folder if it doesn't exist
if [ ! -d $dotfilesFolder/i3 ]; then
	mkdir $dotfilesFolder/i3
fi

# Copy the file
cp ~/.i3/config $dotfilesFolder/i3/config

# i3blocks
# Create i3blocks folder if it doesn't exist
if [ ! -d $dotfilesFolder/i3/i3blocks ]; then
	mkdir $dotfilesFolder/i3/i3blocks
fi

# Copy the file
cp ~/.i3/i3blocks/.i3blocks.conf $dotfilesFolder/i3/i3blocks/i3blocks.conf

# Fish
# Create fish folder if it doesn't exist
if [ ! -d $dotfilesFolder/fish ]; then
	mkdir $dotfilesFolder/fish
fi

# Copy the files
if [ ! -d $dotfilesFolder/fish/conf.d ]; then
    cp -r ~/.config/fish/conf.d $dotfilesFolder/fish/conf.d
    cp ~/.config/fish/fish_variables $dotfilesFolder/fish/fish_variables
fi

# Tmux
# Copy .tmux.conf
cp ~/.tmux.conf $dotfilesFolder/tmux.conf

# Compton
# Copy .compton.conf
cp ~/.config/compton.conf $dotfilesFolder/compton.conf

# Polybar
# Copy polybar folder
cp -r ~/.config/polybar $dotfilesFolder/polybar

# Commit and push
git --git-dir $dotfilesFolder/.git --work-tree $dotfilesFolder add .
git --git-dir $dotfilesFolder/.git --work-tree $dotfilesFolder commit -m "Dotfiles Updated at: $(date)"
git --git-dir $dotfilesFolder/.git --work-tree $dotfilesFolder push

notify-send "Dotfiles Updated!"
