#! /bin/sh
# Get the list of passwords and copy them to the clipboard
# Author: Aseem Lalfakawma
# Website: alalfakawma.me
# Github: https://github.com/alalfakawma

# Get all the passwords and remove the unicode chars and then trim the strings
pass=$(pass show | iconv -c -f utf-8 -t ascii | xargs)

# Convert the output string to an array
passArray=($pass)

# Remove first 2 elements which are useless
unset 'passArray[0]'
unset 'passArray[1]'

# Print the array to the rofi script
selected=$(printf '%s\n' "${passArray[@]}" | rofi -theme ~/.config/rofi/rainbow.rasi -dmenu -i -p "Select site")
if [ $selected ]; then
    $(pass -c $selected > /dev/null)
    notify-send "$selected password copied to clipboard for 45 seconds!"
fi
